name: CARLITOS CI
on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Repositorio
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm install --global yarn
      - run: CI=false
      - run: yarn install
      - run: yarn build

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          #ARGS: "-rltgoDzvO --delete"
          ARGS: "-rlgoDzvc -i"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          #TARGET: ${{ secrets.REMOTE_TARGET }}
          TARGET: /www/wwwroot/adm.insiderhof.com.br/ 

      # - name: Post Deploy
      #   uses: appleboy/ssh-action@master
      #   with:
      #       host: ${{ secrets.REMOTE_HOST }}
      #       username: ${{ secrets.REMOTE_USER }}
      #       key: ${{ secrets.SSH_PRIVATE_KEY }}
      #       port: ${{ secrets.REMOTE_PORT }}
      #       # script: | 
      #       #   cd /home/wwinst/nodeapp_test
      #       #   yarn restart
      
    